// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TestingWASM.Shared.Data.Entities
{
    [Table("FollowUpQuestion")]
    public partial class FollowUpQuestion
    {
        public FollowUpQuestion()
        {
            FormFollowupQuestionEntries = new HashSet<FormFollowupQuestionEntry>();
            QuestionResponseOptionFollowUpQuestionMaps = new HashSet<QuestionResponseOptionFollowUpQuestionMap>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string Prompt { get; set; }
        [Column("QuestionResponseID")]
        public int QuestionResponseId { get; set; }
        [StringLength(15)]
        public string DefaultResponse { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime AddTimeStamp { get; set; }
        [Required]
        [StringLength(50)]
        public string AddUser { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ChangeTimeStamp { get; set; }
        [Required]
        [StringLength(50)]
        public string ChangeUser { get; set; }

        [ForeignKey(nameof(QuestionResponseId))]
        [InverseProperty("FollowUpQuestions")]
        public virtual QuestionResponse QuestionResponse { get; set; }
        [InverseProperty(nameof(FormFollowupQuestionEntry.FollowUpQuestion))]
        public virtual ICollection<FormFollowupQuestionEntry> FormFollowupQuestionEntries { get; set; }
        [InverseProperty(nameof(QuestionResponseOptionFollowUpQuestionMap.FollowUpQuestion))]
        public virtual ICollection<QuestionResponseOptionFollowUpQuestionMap> QuestionResponseOptionFollowUpQuestionMaps { get; set; }
    }
}