// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TestingWASM.Shared.Data.Entities
{
    [Table("FormType")]
    public partial class FormType
    {
        public FormType()
        {
            FormQuestions = new HashSet<FormQuestion>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string Title { get; set; }
        [Required]
        [StringLength(15)]
        public string ShortName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime EndDate { get; set; }
        public int SortOrder { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime AddTimeStamp { get; set; }
        [Required]
        [StringLength(50)]
        public string AddUser { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ChangeTimeStamp { get; set; }
        [Required]
        [StringLength(50)]
        public string ChangeUser { get; set; }

        [InverseProperty(nameof(FormEntry.FormType))]
        public virtual ICollection<FormEntry> FormEntries { get; set; }
        [InverseProperty(nameof(FormQuestion.FormType))]
        public virtual ICollection<FormQuestion> FormQuestions { get; set; }
    }
}