// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TestingWASM.Shared.Data.Entities
{
    [Table("FormFollowupQuestionEntry")]
    public partial class FormFollowupQuestionEntry
    {
        [Key]
        public int Id { get; set; }
        [Column("FormQuestionEntryID")]
        public int FormQuestionEntryId { get; set; }
        [Column("FollowUpQuestionID")]
        public int FollowUpQuestionId { get; set; }
        [Required]
        [StringLength(500)]
        public string ResponesValue { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime AddTimeStamp { get; set; }
        [Required]
        [StringLength(50)]
        public string AddUser { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ChangeTimeStamp { get; set; }
        [Required]
        [StringLength(50)]
        public string ChangeUser { get; set; }

        [ForeignKey(nameof(FollowUpQuestionId))]
        [InverseProperty("FormFollowupQuestionEntries")]
        public virtual FollowUpQuestion FollowUpQuestion { get; set; }
        [ForeignKey(nameof(FormQuestionEntryId))]
        [InverseProperty("FormFollowupQuestionEntries")]
        public virtual FormQuestionEntry FormQuestionEntry { get; set; }
    }
}