// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TestingWASM.Shared.Data.Entities
{
    [Table("QuestionResponse")]
    public partial class QuestionResponse
    {
        public QuestionResponse()
        {
          
            FormQuestions = new HashSet<FormQuestion>();
            QuestionResponseOptions = new HashSet<QuestionResponseOption>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string TypeOfResponse { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime AddTimeStamp { get; set; }
        [Required]
        [StringLength(50)]
        public string AddUser { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ChangeTimeStamp { get; set; }
        [Required]
        [StringLength(50)]
        public string ChangeUser { get; set; }


     
        public virtual ICollection<FormQuestion> FormQuestions { get; set; }

        [InverseProperty(nameof(QuestionResponseOption.QuestionResponse))]
        public virtual ICollection<QuestionResponseOption> QuestionResponseOptions { get; set; }
    }
}