// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Example2.Shared.Data.Entities
{
    [Table("Question")]
    [Index(nameof(Id), Name = "IX_Question", IsUnique = true)]
    public partial class Question
    {
        public Question()
        {
            FormQuestions = new HashSet<FormQuestion>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(1000)]
        public string Text { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime EndDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime AddTimeStamp { get; set; }
        [Required]
        [StringLength(50)]
        public string AddUser { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ChangeTimeStamp { get; set; }
        [Required]
        [StringLength(50)]
        public string ChangeUser { get; set; }

        [InverseProperty(nameof(FormQuestion.Question))]
        public virtual ICollection<FormQuestion> FormQuestions { get; set; }
    }
}