// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TestingWASM.Shared.Data.Entities
{
    [Table("QuestionResponseOption")]
    public partial class QuestionResponseOption
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("QuestionResponseID")]
        public int QuestionResponseId { get; set; }
        [Required]
        [StringLength(50)]
        public string ShortDescription { get; set; }
        [Required]
        [StringLength(150)]
        public string LongDescription { get; set; }
        public int SortOrder { get; set; }
        [Column(TypeName = "date")]
        public DateTime EffectiveDate { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ExpirationDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime AddTimeStamp { get; set; }
        [Required]
        [StringLength(50)]
        public string AddUser { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ChangeTimeStamp { get; set; }
        [Required]
        [StringLength(50)]
        public string ChangeUser { get; set; }

        [ForeignKey(nameof(QuestionResponseId))]
        [InverseProperty("QuestionResponseOptions")]
        public virtual QuestionResponse QuestionResponse { get; set; }

       
    }
}